// what we generate according to your .proto definition.
package my_gen

import (
	"context"

	"github.com/naoyafurudono/proto-cli/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
	"github.com/naoyafurudono/proto-cli/lib"
	"github.com/spf13/cobra"
)

// CLI implementation (what we generate)
func NewGreetCommand(ctx context.Context, s greetv1connect.GreetServiceHandler) *cobra.Command {
	var greetService = &cobra.Command{
		Use:   "great",
		Short: "Important service.",
		Long:  "Important service.",
	}
	var reqData *string = greetService.PersistentFlags().StringP("data", "d", "{}", "request message represented as a JSON")

	greetServiceHello := lib.RpcCommand(ctx,
		s.Hello,
		"hello",
		"basic greeting",
		"basic greeting",
		reqData,
	)
	greetServiceThanks := lib.RpcCommand(ctx,
		s.Thanks,
		"thanks",
		"you cannot live alone",
		"you cannot live alone",
		reqData,
	)

	greetService.AddCommand(
		greetServiceHello,
		greetServiceThanks,
	)
	return greetService
}
